spring:
  application:
    name: hotel-booking-system
  
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_booking_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # OAuth2 Configuration - Uncomment and configure when you want to enable GitHub login
  # security:
  #   oauth2:
  #     client:
  #       registration:
  #         github:
  #           client-id: Ov23likMwfQLsGH9E40I
  #           client-secret: eeab2b1c67fc06c98ac358cc1a75658014b947e5
  #           scope:
  #             - user:email
  #             - read:user
  #       provider:
  #         github:
  #           authorization-uri: https://github.com/login/oauth/authorize
  #           token-uri: https://github.com/login/oauth/access_token
  #           user-info-uri: https://api.github.com/user
  #           user-name-attribute: id


server:
  port: 8080

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-secret-key-change-this-in-production-minimum-256-bits}
  expiration: 86400000 # 24 hours in milliseconds

# Razorpay Configuration
razorpay:
  key:
    id: ${RAZORPAY_KEY_ID:your-razorpay-key-id}
    secret: ${RAZORPAY_KEY_SECRET:your-razorpay-key-secret}

# Application Configuration
app:
  frontend:
    url: http://localhost:8080
